### ISSUE TITLE
Cannot use adwaita components

### ISSUE THREAD

**Issue by tizu69** [diamondburned/gotk4-adwaita#14]
```go
package main

import (
	"os"

	"github.com/diamondburned/gotk4-adwaita/pkg/adw"
	"github.com/diamondburned/gotk4/pkg/gio/v2"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

func main() {
	app := gtk.NewApplication("com.github.tizu69.test", gio.ApplicationFlagsNone)
	app.Connect("activate", func() {
		adw.Init()
		activate(app)
	})

	if code := app.Run(os.Args); code > 0 {
		os.Exit(code)
	}
}

func activate(app *gtk.Application) {
	label := gtk.NewLabel("Hello World")

	window := adw.NewApplicationWindow(app)
	window.SetChild(label)
	window.Show()
}
```

This errors:

```
2024/07/25 15:56:50 ERROR gtk_window_set_child() is not supported for AdwApplicationWindow glib_old_log_api=1 priority=3 glib_domain=Adwaita
```

**Comment by diamondburned** [comment]
You want `window.SetContent`: https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/method.Window.set_content.html

**Comment by tizu69** [comment]
oh my- ok fuck, I assumed the issue was that the mappings prefixed stuff with gtk_ instead of adw_, thanks @diamondburned 

edit: is there a reason why SetChild is a valid method then? Or does the application window override gtk_window_set_child() to error, without the mappings have this documented?

**Comment by diamondburned** [comment]
> is there a reason why SetChild is a valid method then? Or does the application window override gtk_window_set_child() to error, without the mappings have this documented?

This is kind of what it does, but it's similar. libadwaita uses its own child for the window, so calling `SetChild` would be replacing that child. There's a check for this: https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/src/adw-application-window.c?ref_type=heads#L104.
