### ISSUE TITLE
Simple hello world for this package?

### ISSUE THREAD

**Issue by ismyhc** [diamondburned/gotk4-adwaita#4]
Hi.

Sorry for the  newb question, but is there a simple example (hello world) of how to use this? Ive ran the example apps for go-gtk4 but not quite sure how I would use this package.

Thanks!

**Comment by diamondburned** [comment]
If you follow [gotk4-examples/gtk4/simple](https://github.com/diamondburned/gotk4-examples/blob/master/gtk4/simple/main.go) but replace `gtk.Application` with `adw.Application` and `gtk.ApplicationWindow` with `adw.ApplicationWindow`, it should work.

Unfortunately, I don't have any ready-made gotk4-adwaita examples to show.

**Comment by ismyhc** [comment]
> If you follow [gotk4-examples/gtk4/simple](https://github.com/diamondburned/gotk4-examples/blob/master/gtk4/simple/main.go) but replace `gtk.Application` with `adw.Application` and `gtk.ApplicationWindow` with `adw.ApplicationWindow`, it should work.
> 
> Unfortunately, I don't have any ready-made gotk4-adwaita examples to show.

Thank you was able to figure out.
